# Generated by Django 5.2 on 2026-03-17 09:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ref', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('from_stop', models.CharField(max_length=200)),
                ('to_stop', models.CharField(max_length=200)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('charge', models.CharField(blank=True, max_length=50)),
                ('interval', models.CharField(blank=True, max_length=50)),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_routes', to='routes.busstop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'stop')},
            },
        ),
        migrations.AddField(
            model_name='busstop',
            name='routes',
            field=models.ManyToManyField(related_name='stops', through='routes.RouteStop', to='routes.busroute'),
        ),
    ]
